CREATE TABLE SURVEYRESULT 
(
  ID NUMBER(38) GENERATED ALWAYS AS IDENTITY INCREMENT BY 1 START WITH 1 NOT NULL 
, SURVEYID NUMBER(38) 
, OPTIONID NUMBER(38) 
, OPTIONTYPE NUMBER(38) 
, OPTIONVALUE NUMBER(38) 
, OCOMMENT VARCHAR2(255) 
, CONSTRAINT SURVEYRESULT_PK PRIMARY KEY 
  (
    ID 
  )
  ENABLE 
);

CREATE TRIGGER SURVEYRESULT_TRG 
BEFORE INSERT ON SURVEYRESULT 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.OCOMMENT IS NULL THEN
      SELECT SURVEYRESULT_SEQ.NEXTVAL INTO :NEW.OCOMMENT FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
/
