INSERT INTO DC_SOCPEN (BENEFICIARY_ID, CHILD_ID, NAME, SURNAME,  GRANT_TYPE, REGION_ID, APPLICATION_DATE, STATUS_CODE, PAYPOINT) 
SELECT     
    DISTINCT c.PENSION_NO  AS BENEFICIARY_ID,
    c.ID_NO AS CHILD_ID,
    B.NAME_EXT,
    B.SURNAME_EXT,
    C.GRANT_TYPE AS GRANT_TYPE,
    D.REGION_CODE AS REGION_ID,
    C.APPLICATION_DATE AS APPLICATION_DATE,
    C.STATUS_CODE,
    B.secondary_paypoint as paypoint  
FROM SASSA.socpen_personal_grants a
LEFT JOIN SASSA.SOCPEN_PERSONAL B ON  a.PENSION_NO = b.PENSION_NO
INNER JOIN VW_P12_CHILDREN c ON c.PENSION_NO = a.PENSION_NO
LEFT JOIN SASSA.cust_rescodes D ON b.secondary_paypoint = d.res_code
where NOT exists(SELECT 1 FROM DC_Socpen x WHERE x.Beneficiary_id = c.PENSION_NO AND x.grant_type = c.GRANT_TYPE and x.Child_Id = c.ID_NO)