UPDATE DC_SOCPEN
SET STATUS_CODE = 'INACTIVE'
WHERE STATUS_CODE = 'ACTIVE';

COMMIT;

UPDATE DC_SOCPEN
SET STATUS_CODE = 'ACTIVE'
WHERE (beneficiary_id,GRANT_TYPE) in (SELECT ID_NUMBER, GRANT_TYPE FROM CUST_PAYMENT);

COMMIT;